# Generated by Django 3.2.3 on 2021-06-22 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='Tipo_consulta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'contacto'], [2, 'reclamo'], [3, 'sugerencia'], [3, 'felicitaciones']], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
